### ISSUE TITLE
Linux fails to compile at cmake .. due to missing wxWidgets, despite it being installed

### ISSUE THREAD

**Issue by ImperatorStorm** [sandsmark/AGE#1]
Building at `cmake ..` stage fails with ```-- Defaulting to wx-config name wx-config-gtk3
CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:577 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.19/Modules/FindwxWidgets.cmake:1016 (find_package_handle_standard_args)
  CMakeLists.txt:38 (find_package)``` despite having compiled wxgtk2-dev with instructions directly from [AUR page for the package](https://aur.archlinux.org/packages/wxgtk2-dev/)

**Comment by sandsmark** [comment]
I just use the default cmake wxwidgets config thing, so this sounds like an issue with wxgtk-dev (and I've tested with wxgtk2, wxgtk3 and wxqt-dev from aur, so it seems pretty robust).

But it seems like you have it installed in /usr/local, not in the standard path?

Any specific reason for not using wxgtk2 in the `extra` repo? And could you check the difference between the PKGBUILD for wxgtk-dev and the official PKGBUILDs in extra?

**Comment by ImperatorStorm** [comment]
yep, issue was due to me not installing into /usr/local
